

#ifndef CONSTANTS_H
#define CONSTANTS_H

#define HASH_SIZE 26
#define HASH_START 65

#define TYPE_FICTION "FICTION"
#define TYPE_CHILDREN "CHILDREN"
#define TYPE_PERIODICAL "PERIODICAL"

#define FICTION_CODE 'F'
#define CHILDREN_CODE 'C'
#define PERIODICAL_CODE 'P'

#define COUNT_MAX_LENGTH (COUNT_BUFFER - 2)
#define TITLE_MAX_LENGTH (TITLE_BUFFER - 2)
#define AUTHOR_MAX_LENGTH (AUTHOR_BUFFER - 2)
#define YEAR_MAX_LENGTH (YEAR_BUFFER - 2)
#define MONTH_MAX_LENGTH (MONTH_BUFFER - 2)

#define COMMAND_BUFFER 10

#define COUNT_BUFFER 6
#define TITLE_BUFFER 38
#define AUTHOR_BUFFER 24
#define YEAR_BUFFER 6
#define MONTH_BUFFER 6

#define CHECKOUT_CODE 'C'
#define RETURN_CODE 'R'
#define DISPLAY_LIB_CODE 'D'
#define DISPLAY_PAT_CODE 'H'

#define TYPE_CHECKOUT "CHECKOUT"
#define TYPE_RETURN "RETURN"
#define TYPE_DISPLAY_LIB "DISPLAY LIBRARY"
#define TYPE_DISPLAY_PATRON "DISPLAY PATRON"

#endif