

#ifndef CONSTANTS_H
#define CONSTANTS_H

#define HASH_SIZE 26
#define HASH_START 65

#define TYPE_FICTION "FICTION"
#define TYPE_CHILDREN "CHILDREN"
#define TYPE_PERIODICAL "PERIODICAL"

#define FICTION_CODE 'F'
#define CHILDREN_CODE 'C'
#define PERIODICAL_CODE 'P'

#define COUNT_MAX_LENGTH 6
#define TITLE_MAX_LENGTH 24
#define AUTHOR_MAX_LENGTH 38
#define YEAR_MAX_LENGTH 4



#endif